name: Daily Inspirational Quote
on:
  issues:
    types:
      - opened

jobs:
  generate_quote:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate quote
        run: |
          quote=$(curl -s https://api.quotable.io/random | jq -r '.content')
          echo "$quote" > quote.txt
          echo "Generated quote: $quote"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add quote.txt
          git commit -m "Add daily inspirational quote [skip ci]"
          git push
