name: Celebratory GIF

on:
  issues:
    types:
      - closed

jobs:
  celebrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment with celebratory GIF
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ctx = github.context;

            const commentBody = `🎉 This issue has been closed! Enjoy this celebratory GIF: ![Celebration](${https://media.tenor.com/LCJNz0f5t1sAAAAC/racc-racc-did-it.gif})`;
            github.issues.createComment({
                issue_number: ctx.issue.number,
                owner: ctx.repo.owner,
                repo: ctx.repo.repo,
                body: commentBody
              });

