name: Comment on Closed Issue with GIF

on:
  issues:
    types:
      - closed

jobs:
  commentOnClosedIssue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment with GIF
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const gifImage = '![GIF Image](https://github.com/Sahil1479/OpenSourceDemo/blob/master/celebration-gif.gif)';
            const commentBody = `${gifImage}\n\nThis issue has been closed.`;
            
            const { data: comment } = await github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
