name: Daily Inspirational Quote
on:
  issues:
    types:
      - opened

jobs:
  generate_quote:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate quote
        run: |
          echo "::set-output name=quote::$(curl -s https://api.quotable.io/random | jq -r '.content')"

      - name: Save quote to file
        run: |
          echo "${{ steps.generate_quote.outputs.quote }}" > quote.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add quote.txt
          git commit -m "Add daily inspirational quote [skip ci]"
          git push
