name: Add Comment to New Issue
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Comment to New Issue
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue.number;
            const comment = `Thank you for creating this issue! We will look into it.`;
            const octokit = github.getOctokit(token);

            octokit.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: comment
            });
