name: Add Comment to New Issue
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Comment to New Issue
        run: |
          owner=$(jq -r ".repository.owner.login" "$GITHUB_EVENT_PATH")
          repo=$(jq -r ".repository.name" "$GITHUB_EVENT_PATH")
          issueNumber=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
          comment="Thank you for creating this issue! We will look into it."

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$comment\"}" \
            "https://api.github.com/repos/$owner/$repo/issues/$issueNumber/comments"
